PYCBC-496: Fix crash when calling Cluster.cluster_manager()
Motivation
----------
When calling the `cluster_manager()` method of a `Cluster`, the
application will throw an authentication exception.

Example code:

```
from couchbase.cluster import Cluster, PasswordAuthenticator

cluster = Cluster('couchbase://localhost:8091')
cluster.authenticate(PasswordAuthenticator('Administrator', 'password'))

admin = cluster.cluster_manager()
```

Stack trace:

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    admin = cluster.cluster_manager()
  File "/home/vagrant/couchbase-python-client/couchbase/cluster.py", line 117, in cluster_manager
    return Admin(username, password, connection_string=connection_string)
  File "/home/vagrant/couchbase-python-client/couchbase/admin.py", line 91, in __init__
    super(Admin, self).__init__(**kwargs)
couchbase.exceptions.NotSupportedError: <RC=0x13[Operation not supported], Couldn't create instance. Either bad credentials/hosts/bucket names were passed, or there was an internal error in creating the object, C Source=(src/bucket.c,923)>
```

This is because the connection string becomes mangled in the code
within the `Admin` object constructor.

Modifications
-------------
Only construct the connection string for the `Admin` class if a
connection string has not been explicitly passed in.

Added a test to cover this specific case, to handle any regression in
future.

Result
------
Running the `cluster_manager()` method of a `Cluster` object succeeds
and works as expected.

Change-Id: I0a87047332fb725617210b40d57885bc01b6de00
Reviewed-on: http://review.couchbase.org/95314
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Ellis Breen <ellis.breen@couchbase.com>